"""create wallet and operations tables

Revision ID: 50a085bf1ccf
Revises:
Create Date: 2025-10-31 14:09:57.458732

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "50a085bf1ccf"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS wallet")

    op.create_table(
        "wallet",
        sa.Column("uuid", sa.String(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.PrimaryKeyConstraint("uuid"),
        schema="wallet",
    )
    op.create_table(
        "operation",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("wallet_uuid", sa.String(), nullable=True),
        sa.Column(
            "operation_type",
            sa.Enum("DEPOSIT", "WITHDRAW", name="operationtype"),
            nullable=True,
        ),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=True),
        sa.ForeignKeyConstraint(
            ["wallet_uuid"],
            ["wallet.wallet.uuid"],
        ),
        sa.PrimaryKeyConstraint("id"),
        schema="wallet",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("operation", schema="wallet")
    op.drop_table("wallet", schema="wallet")
    # ### end Alembic commands ###
